### ISSUE TITLE
Broken doc target

### ISSUE THREAD

**Issue by vitaut** [ampl/mp#67]
```
> ninja doc
ninja: warning: multiple rules generate src/asl/arith.h. builds involving this target will not be correct; continuing anyway
ninja: error: '../doc/extract-docs.py', needed by 'doc/html/index.html', missing and no known rule to make it
```

**Comment by vitaut** [comment]
Installation of sphinx fails on Travis:

```
setuptools;__file__='/tmp/tmpyQi5DQ/build/virtualenv/build/sphinx/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-RHTDJ3-record/install-record.txt --install-headers /tmp/tmpyQi5DQ/build/virtualenv/include/site/python2.7 failed with error code 1 in /tmp/tmpyQi5DQ/build/virtualenv/build/sphinx
Storing complete log in /home/travis/.pip/pip.log
Traceback (most recent call last):
  File "support/travis-build.py", line 23, in <module>
    returncode, repo_dir = __import__('build-docs').build_docs(workdir, doxygen)
  File "/home/travis/build/ampl/mp/support/build-docs.py", line 73, in build_docs
    pip_install('sphinx==1.3.1')
  File "/home/travis/build/ampl/mp/support/build-docs.py", line 48, in pip_install
    check_call(['pip', 'install', '-q', package])
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'install', '-q', 'sphinx==1.3.1']' returned non-zero exit status 1
```

**Comment by vitaut** [comment]
Fixed in https://github.com/ampl/mp/commit/2dbb9c4de0bcfa87a057052f1102820a2556b680. Relocatable virtualenv is not relocatable if you want pip to work.
