### ISSUE TITLE
build doc failure

### ISSUE THREAD

**Issue by opoplawski** [ampl/mp#71]
Trying to update Fedora package to latest git.  Getting the following:
~~~~~
Scanning dependencies of target doc
make[3]: Leaving directory '/builddir/build/BUILD/mp-635f5525aeae319a63e97ee26226897dd15ca8bc/build'
make -f doc/CMakeFiles/doc.dir/build.make doc/CMakeFiles/doc.dir/build
make[3]: Entering directory '/builddir/build/BUILD/mp-635f5525aeae319a63e97ee26226897dd15ca8bc/build'
[ 14%] Generating amplgsl/elementary.rst, amplgsl/special.rst, amplgsl/airy.rst, amplgsl/bessel.rst, amplgsl/clausen.rst, amplgsl/coulomb.rst, amplgsl/coupling.rst, amplgsl/dawson.rst, amplgsl/debye.rst, amplgsl/dilog.rst, amplgsl/ellint.rst, amplgsl/erf.rst, amplgsl/expint.rst, amplgsl/fermi-dirac.rst, amplgsl/gamma-beta.rst, amplgsl/gegenpoly.rst, amplgsl/hyperg.rst, amplgsl/laguerre.rst, amplgsl/lambert.rst, amplgsl/legendre.rst, amplgsl/log.rst, amplgsl/mathieu.rst, amplgsl/pow.rst, amplgsl/psi.rst, amplgsl/synchrotron.rst, amplgsl/transport.rst, amplgsl/zeta.rst, amplgsl/sf-refs.rst, amplgsl/randist.rst, amplgsl/ran-intro.rst, amplgsl/ran-gaussian.rst, amplgsl/ran-gaussian-tail.rst, amplgsl/ran-exponential.rst, amplgsl/ran-laplace.rst, amplgsl/ran-exppow.rst, amplgsl/ran-cauchy.rst, amplgsl/ran-rayleigh.rst, amplgsl/ran-rayleigh-tail.rst, amplgsl/ran-landau.rst, amplgsl/ran-levy.rst, amplgsl/ran-levy-skew.rst, amplgsl/ran-gamma.rst, amplgsl/ran-flat.rst, amplgsl/ran-lognormal.rst, amplgsl/ran-chisq.rst, amplgsl/ran-fdist.rst, amplgsl/ran-tdist.rst, amplgsl/ran-beta.rst, amplgsl/ran-logistic.rst, amplgsl/ran-pareto.rst, amplgsl/ran-weibull.rst, amplgsl/ran-gumbel1.rst, amplgsl/ran-gumbel2.rst, amplgsl/ran-poisson.rst, amplgsl/ran-bernoulli.rst, amplgsl/ran-binomial.rst, amplgsl/ran-negative-binomial.rst, amplgsl/ran-pascal.rst, amplgsl/ran-geometric.rst, amplgsl/ran-hypergeometric.rst, amplgsl/ran-logarithmic.rst, amplgsl/ran-refs.rst
cd /builddir/build/BUILD/mp-635f5525aeae319a63e97ee26226897dd15ca8bc/build/doc && /builddir/build/BUILD/mp-635f5525aeae319a63e97ee26226897dd15ca8bc/support/build-docs.py extract-docs
Traceback (most recent call last):
  File "/builddir/build/BUILD/mp-635f5525aeae319a63e97ee26226897dd15ca8bc/support/build-docs.py", line 145, in <module>
    extract_docs(args['<file>'], '.')
  File "/builddir/build/BUILD/mp-635f5525aeae319a63e97ee26226897dd15ca8bc/support/build-docs.py", line 38, in extract_docs
    with open(filename, 'r+b') as input:
TypeError: coercing to Unicode: need string or buffer, NoneType found
doc/CMakeFiles/doc.dir/build.make:213: recipe for target 'doc/amplgsl/elementary.rst' failed
~~~~~

**Comment by vitaut** [comment]
Fixed in https://github.com/ampl/mp/commit/8fd98eab49867f4de01025bc311b9e47a4c39371. Thanks for reporting!

**Comment by opoplawski** [comment]
That seemed to do the trick.  Thanks again.   Also, it looks like all docs need to get installed manually, or is there a make target?

**Comment by vitaut** [comment]
I've just added documentation to the install target in https://github.com/ampl/mp/commit/b83573e05b240890c21a00f1f8bc3e8186b96af0. Now it should be installed under `${CMAKE_INSTALL_PREFIX}/share/doc/mp`.
