### ISSUE TITLE
Missing default values for arguments in apidocs

### ISSUE THREAD

**Issue by vitaut** [ampl/mp#91]
Default values for `flags` are missing in http://ampl.github.io/nl-reader.html#_CPPv2N2mp10ReadNLFileEN3fmt10CStringRefER7Handleri and http://ampl.github.io/nl-reader.html#_CPPv2N2mp12ReadNLStringE11NLStringRefR7HandlerN3fmt10CStringRefEi.

**Comment by vitaut** [comment]
Trying to build the docs with breathe master:

```
# Sphinx version: 1.5a0
# Python version: 2.7.6 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   reading sources... [ 82%] amplgsl/randist
#   reading sources... [ 83%] amplgsl/rng
#   reading sources... [ 85%] amplgsl/sf-refs
#   reading sources... [ 86%] amplgsl/special
#   reading sources... [ 87%] amplgsl/synchrotron
#   reading sources... [ 88%] amplgsl/transport
#   reading sources... [ 90%] amplgsl/zeta
#   reading sources... [ 91%] common
#   reading sources... [ 92%] index
#   reading sources... [ 93%] nl-reader
# Loaded extensions:
#   breathe (4.1.0) from doc/build/virtualenv/local/lib/python2.7/site-packages/breathe/__init__.pyc
#   sphinx.ext.mathjax (1.5a0) from doc/build/virtualenv/local/lib/python2.7/site-packages/sphinx/ext/mathjax.pyc
#   alabaster (0.7.7) from doc/build/virtualenv/local/lib/python2.7/site-packages/alabaster/__init__.pyc
Traceback (most recent call last):
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/sphinx/environment.py", line 548, in update
    self._read_serial(docnames, app)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/sphinx/environment.py", line 568, in _read_serial
    self.read_doc(docname, app)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/sphinx/environment.py", line 721, in read_doc
    pub.publish()
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/sphinx/io.py", line 49, in read
    self.parse()
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2301, in explicit_markup
    self.explicit_list(blank_finish)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2331, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2604, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/breathe/directives.py", line 314, in run
    self.directive_args)
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/breathe/directive/base.py", line 86, in render
    return object_renderer.render()
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/breathe/renderer/index.py", line 63, in render
    rendered_data = data_renderer.render()
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 39, in render
    return compound_renderer.render()
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 143, in render
    nodelist.extend(renderIterable(self, self.data_object.innerclass))
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 21, in renderIterable
    output.extend(child_renderer.render())
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/breathe/renderer/index.py", line 63, in render
    rendered_data = data_renderer.render()
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 39, in render
    return compound_renderer.render()
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 123, in render
    child_nodes = renderer.render()
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 160, in render
    node_list.extend(renderIterable(self, self.data_object.memberdef))
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 21, in renderIterable
    output.extend(child_renderer.render())
  File "doc/build/virtualenv/local/lib/python2.7/site-packages/breathe/renderer/compound.py", line 335, in render
    signode, contentnode = node.children
ValueError: too many values to unpack
```

**Comment by vitaut** [comment]
Fixed but need to merge the fix upstream (https://github.com/michaeljones/breathe/pull/240).

**Comment by vitaut** [comment]
Merged upstream.
